### PR TITLE
Added reviews

### LINKED ISSUE #15: When search query doesn't match any products empty page is shown without any messages.

### PR DESCRIPTION
**Pull request by martiis**
We have unused reviews data, written simple twig extension for demonstration purposes.

Also closes #15.

P.S. we can also add Wine rating form that could demonstrate symfony forms and inserting new data into Elasticsearch index.

### CODE REVIEW

**Comment by MindaugasR** [comment]
Is this PR still actual?

**Comment by saimaz** [comment]
Yes it is.

**Comment by tautrimas** [comment]
@martiis: this is hanging very long. Can you make it QAable?

**Comment by trylika** [comment]
Guys???? @martiis @saimaz

**Pull request closed without merging**
