### PR TITLE
added ongr.io splash in vagrant install.sh

### PR DESCRIPTION
**Pull request by martiis**
Looks cool :)

screenshot from 2015-01-25 17 14 21

### CODE REVIEW

**Comment by gyKa** [comment]
I suggest to add this in the file `/etc/motd` as well :wink:

**Comment by martiis** [comment]
What does it do? :open_mouth:

**Comment by gyKa** [comment]
When you execute `vagrant ssh` command, you will be greeted with uname, MOTD (message of the day, you can see this text in file /etc/motd), mailbox status and last login information. It can be replaced by nice ongr.io logo :smirk: 

```
09:45 $ vagrant ssh
Linux ongr 3.2.0-4-amd64 #1 SMP Debian 3.2.54-2 x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
You have mail.
Last login: Fri Jan 23 08:28:56 2015 from 10.0.2.2
```

**Comment by saimaz** [comment]
Good idea @gyKa but for this we would need to add this via puppet. And this means that it will go to some production servers if we will reuse puppet manifests. It's nice suggestion but its completely not necessary IMO.

**Pull request merged**
